Bài 1
Yêu cầu:
•Tạo một vector chứa các số từ 1 đến 16.
• Sử dụng `reshape` để biến nó thành ma trận 4x4.
•Trích xuất ma trận 2x2 ở góc dưới bên phải (các phần tử 11, 
12, 15, 16).

In [1]:
import numpy as np
vector_1chieu = np.arange(1, 17)
print("Ma tran 1 chiều gốc ( Shape :", vector_1chieu.shape, ")")
print(vector_1chieu)
matrix_4x4 = vector_1chieu.reshape(4, 4)
print(" Ma tran 4x4 sau khi reshape ( Shape :",matrix_4x4,")")
print(matrix_4x4)

matrix_phu = matrix_4x4[2:,2:]
print("Ma trận được trích xuất là :")
print(matrix_phu)


Ma tran 1 chiều gốc ( Shape : (16,) )
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 Ma tran 4x4 sau khi reshape ( Shape : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] )
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Ma trận được trích xuất là :
[[11 12]
 [15 16]]


Bài 2
•
Tạo một ma trận 3x3 chứa các số nguyên ngẫu nhiên từ 1 
đến 20.
•
Tính giá trị trung bình (mean) của toàn bộ ma trận.
•
Tìm giá trị lớn nhất (max) của mỗi hàng (sử dụng `axis=1`).

In [2]:
import numpy as np
np.random.seed(36)
matrix_3x3 = np.random.randint(1, 36, size=(3, 3))
print("Ma trận 3x3 ngẫu nhiên:")
print(matrix_3x3)
trung_binh = np.mean(matrix_3x3)
print("Giá trị trung bình của ma trận:", trung_binh)
max_hang = np.max(matrix_3x3, axis=1)
print("Giá trị lớn nhất của mỗi hàng:", max_hang)
print(max_hang)

Ma trận 3x3 ngẫu nhiên:
[[ 6 35 31]
 [34 27 10]
 [ 7  1 28]]
Giá trị trung bình của ma trận: 19.88888888888889
Giá trị lớn nhất của mỗi hàng: [35 34 28]
[35 34 28]


Bài tập 3: Phép nhân Ma trận
Cho 2 ma trận:
Tính:
Bài tập 4: Đại số Tuyến tính
Sử dụng ma trận `A` từ Bài tập 3:
Tính:
•a) Tích ma trận: `A @ B`
• b) Tích theo từng phần tử: `A * B`

In [3]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print (" ma trận a là  : ",a)
print (" ma trận b là  : ",b)

tich = a @ b
print("Tích ma trận a @ b là :", tich)

tich_phantu = a * b
print("Tích theo từng phần tử a * b là :", tich_phantu)

 ma trận a là  :  [[1 2]
 [3 4]]
 ma trận b là  :  [[5 6]
 [7 8]]
Tích ma trận a @ b là : [[19 22]
 [43 50]]
Tích theo từng phần tử a * b là : [[ 5 12]
 [21 32]]


Bài tập 4: Đại số Tuyến tính
Sử dụng ma trận `A` từ Bài tập 3:
•a) Ma trận chuyển vị của A (`A.T`).
• b) Ma trận nghịch đảo của A (`np.linalg.inv(A)`)

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print("Ma trận a gốc:", a)

a_T = a.T
print("Ma trận chuyển vị :", a_T)

try:
    a_inv = np.linalg.inv(a)
    print("Ma trận nghịch đảo :", a_inv)
    
    test = a @ a_inv
    print("Kiểm tra:", np.round(test))
except np.linalg.LinAlgError:
    print("Ma trận không khả nghịch")

Ma trận A gốc: [[1 2]
 [3 4]]
Ma trận chuyển vị : [[1 3]
 [2 4]]
Ma trận nghịch đảo : [[-2.   1. ]
 [ 1.5 -0.5]]
Kiểm tra: [[1. 0.]
 [0. 1.]]
